<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>false</UseWindowsForms>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
    <PackageReference Include="FontAwesome.Sharp" Version="6.6.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.2" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="8.0.10" />
    <PackageReference Include="Microsoft.Xaml.Behaviors.Wpf" Version="1.1.135" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\RestaurantShared\RestaurantShared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\RestaurantSynchronizationLib\RestaurantSynchronizationLib.csproj" />
  </ItemGroup>



</Project>